Update validate script

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -1,10 +1,13 @@
 #!/usr/bin/env zsh
 
-echo "Validating scripts:"
+echo "Validating scripts..."
 ./validate.sh
 
 # $? stores exit value of the last command
-if [ $? -ne 0 ]; then
- echo "Cannot validate scripts."
- exit 1
+if [[ $? -ne 0 ]]
+ then
+  echo "Cannot validate scripts - something is wrong."
+  exit 1
+ else
+  echo "Scripts validated successfully."
 fi
